project:
  type: book
  output-dir: docs
  render:
    - index.qmd
    - wk01-mentoring-style.qmd
    - wk02-motivational-style.qmd
    - wk03-leadership-focus.qmd
    - wk04-feedback-orientation.qmd
    - wk05-people-orientation.qmd
    - wk06-leadership-role.qmd
    - wk07-communication-style.qmd
    - wk08-inclusive-mentoring.qmd
    - wk09-conflict-style.qmd
    - wk10-goal-preference.qmd
    - wk11-facilitator.qmd
    - wk12-facilitator-reflection.qmd
    - wk13-self-awareness.qmd
    - references.qmd

book:
  title: "FRI Peer Mentor Mindsets Guide"
  author:
    - "Shane McCarty"
    - "Caitlin Light"
    - "Zihan Hei"
    - "Megan Fegley"
  date: today
  chapters:
    - index.qmd
    - wk01-mentoring-style.qmd
    - wk02-motivational-style.qmd
    - wk03-leadership-focus.qmd
    - wk04-feedback-orientation.qmd
    - wk05-people-orientation.qmd
    - wk06-leadership-role.qmd
    - wk07-communication-style.qmd
    - wk08-inclusive-mentoring.qmd
    - wk09-conflict-style.qmd
    - wk10-goal-preference.qmd
    - wk11-facilitator.qmd
    - wk12-facilitator-reflection.qmd
    - wk13-self-awareness.qmd
    - references.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    number-sections: false
